# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c2b1252bb7b46168c6fc5fb73f05360acb93dc91b2ff29a1e949b3c8c2269f58b45a7dcf4c6c1c12d7da1b5a09ce8dc4282cd4464c05d4692a8e082007ab24

test:
  secret_key_base: 795f4dc40be442e14e004587fb7451755669e9ff9983385afa01e43d16a8d57a2264e2cca0cc959e65338e48aace1aa6a9a57d897b6fa2f34faa732dc9c4ff33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
